<?php
/**
 * Created by PhpStorm.
 * User: stark
 * Date: 2020-11-12
 * Time: 09:28
 */
namespace App\Server;

class Server {
    const REDIS_CONN_NAME = 'redis';
    const PUSH_MSG_SOCKET_FD = 'PUSH_MSG_SOCKET_FD';
    const PUSH_MSG_SSET_USER_LOGIN = 'PUSH_MSG_SSET_USER_LOGIN';
    const MYSQL_CONN_NAME = 'mysql-msg';
    const PUSH_UNREAD_NUMBER_All = 'PUSH_UNREAD_NUMBER_All';
    const PUSH_MSG_COMMENT_LISTS = 'PUSH_MSG_COMMENT_LISTS';
    const PUSH_MSG_NOTICE_SYSTEM = 'PUSH_MSG_NOTICE_SYSTEM';
    const PUSH_MSG_NOTICE_LIST = 'PUSH_MSG_NOTICE_LIST';
    const PUSH_MSG_AUTHOR_LIST = 'PUSH_MSG_AUTHOR_LIST';
    const PUSH_MSG_SIGN_AUTHOR_LIST = 'PUSH_MSG_SIGN_AUTHOR_LIST';
    const PUSH_MSG_AUTHOR_NOTICE_SYSTEM = 'PUSH_MSG_ALL_AUTHOR_NOTICE_SYSTEM';
    const PUSH_MSG_SIGN_AUTHOR_NOTICE_SYSTEM = 'PUSH_MSG_SIGN_AUTHOR_NOTICE_SYSTEM';
}
